name = "web-presentation"
compatibility_date = "2026-05-06"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = "./web-presentation/dist"

[build]
command = "npm run build:cloudflare"
cwd = "."
