export const SLIDE_ICON_IDS = [
  "data",
  "train",
  "test",
  "scaling",
  "encoding",
  "missing-data",
  "leakage",
  "pipeline",
  "regression",
  "classification",
  "tree",
  "forest",
  "svm",
  "clustering",
  "pca",
  "naive-bayes",
  "neural-net",
  "cnn",
  "rnn",
  "backprop",
  "regularization",
  "token",
  "embedding",
  "seq2seq",
  "attention",
  "bert",
  "llm",
  "rag",
  "vector-db",
  "monitoring",
  "formula",
  "table",
  "check",
  "warning",
  "target",
  "feature",
  "model",
  "evaluate",
  "deploy",
  "probability",
  "threshold",
  "kernel",
  "margin",
  "dimension",
  "workflow",
  "nlp",
  "transformer",
  "idea",
  "compare",
  "metric",
] as const;

export type SlideIconId = (typeof SLIDE_ICON_IDS)[number];

export function isSlideIconId(value: string): value is SlideIconId {
  return (SLIDE_ICON_IDS as readonly string[]).includes(value);
}
